config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    :controllers => { registrations: "devise/custom/registrations" }
  root "items#index"
  get "/votes/upvote", to: 'votes#upvote'
  get "/votes/downvote", to: 'votes#downvote'
  get "/ajax/upvote", to: 'votes#ajax_upvote'
  get "/ajax/downvote", to: 'votes#ajax_downvote'

  resources :categories, only: [:show]
  resources :items, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:create, :update, :edit, :destroy]
  end
  resources :admins, only: [:index]
  namespace :admins do
    resources :users, only: [:index, :destroy]
    resources :items, only: [:index, :destroy]
    resources :reviews, only: [:index, :destroy]
  end
end

app/controllers/admins/reviews_controller.rb
class Admins::ReviewsController < AdminsController
  def index
    @items = Item.all
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admins_reviews_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :find_item, only: [:create, :edit, :update, :destroy]

  def create
    @review = @item.reviews.build(review_params)
    if @review.save
      flash[:notice] = "Thanks for the review!"
    else
      flash[:error] = @review.errors.full_messages.join(", ")
    end
    redirect_to item_path(@item)
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.user == current_user
      @review.destroy
    end
    redirect_to item_path(@item)
  end

  def edit
    @review = Review.find(params[:id])
    @rating_options = Review::RATING_OPTIONS
    unless current_user == @review.user
      flash[:error] = "You are not authorized to view this page!"
      redirect_to root_path
    end
  end

  def update
    @review = Review.find(params[:id])
    @rating_options = Review::RATING_OPTIONS
    if @review.update(review_params)
      flash[:notice] = "Review updated successfully!"
      redirect_to item_path(@item)
    else
      flash[:error] = @review.errors.full_messages.join(", ")
      render 'edit'
    end
  end

  private

  def review_params
    params.require(:review).permit(
      :rating,
      :description
    ).merge(
      user_id: current_user.id
    )
  end

  def find_item
    @item = Item.find(params[:item_id])
  end
end

app/views/admins/reviews/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>List of all Reviews</h1>
    <ul>
      <% @items.each do |item| %>
        <li> <%= link_to item.title, item_path(item) %> </li>
          <% unless item.reviews.empty? %>
            <ul>
              <% item.reviews.each do |review| %>
                <li>
                  <%= review.rating %> - <%= review.description %>
                    <div class = "divider"/>
                     <%= button_to "Delete", admins_review_path(:id => review.id),
                      :method => :delete %>
                    </div>
                </li>
                  <ul>
                    <li> Posted By: <%= review.user.email %> </li>
                  </ul>
              <% end %>
            </ul>
          <% end %> </br>
      <% end %>
    </ul>
  </body>
</html>