config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    :controllers => { registrations: "devise/custom/registrations" }
  root "items#index"
  get "/votes/upvote", to: 'votes#upvote'
  get "/votes/downvote", to: 'votes#downvote'
  get "/ajax/upvote", to: 'votes#ajax_upvote'
  get "/ajax/downvote", to: 'votes#ajax_downvote'

  resources :categories, only: [:show]
  resources :items, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:create, :update, :edit, :destroy]
  end
  resources :admins, only: [:index]
  namespace :admins do
    resources :users, only: [:index, :destroy]
    resources :items, only: [:index, :destroy]
    resources :reviews, only: [:index, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_many :votes

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :profile_photo, ProfilePhotoUploader
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == "admin"
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminsController
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.reviews.destroy_all
    flash[:notice] = "#{@user.email} has been deleted!"
    @user.destroy
    redirect_to admins_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end
end

app/views/admins/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>List of all Users</h1>
      <ul>
        <% @users.each do |user| %>
          <li>
            <%= user.email %>
            <div class = "divider"/>
              <%= button_to "Delete", admins_user_path(:id => user.id),
               :method => :delete %>
            </div>
          </li>
        <% end %>
      </ul>
  </body>
</html>