config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    :controllers => { registrations: "devise/custom/registrations" }
  root "items#index"
  get "/votes/upvote", to: 'votes#upvote'
  get "/votes/downvote", to: 'votes#downvote'
  get "/ajax/upvote", to: 'votes#ajax_upvote'
  get "/ajax/downvote", to: 'votes#ajax_downvote'

  resources :categories, only: [:show]
  resources :items, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:create, :update, :edit, :destroy]
  end
  resources :admins, only: [:index]
  namespace :admins do
    resources :users, only: [:index, :destroy]
    resources :items, only: [:index, :destroy]
    resources :reviews, only: [:index, :destroy]
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :reviews
  belongs_to :category

  validates :title, presence: true
  validates :subtitle, presence: true
  validates :category, presence: true
  validates_uniqueness_of :item_url

  def price
    sprintf('$%.2f', read_attribute(:price))
  end

  def self.search(query)
    where { title =~ "#{query}%" }
  end

  def calculate_average_review_score
    rating_sum = reviews.inject(0) { |sum, review| sum + review.rating }
    (rating_sum.to_f / reviews.count).round(2)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < AdminsController
  def index
    @items = Item.all
  end

  def destroy
    @item = Item.find(params[:id])
    if current_user.role = "admin"
      flash[:notice] = "#{@item.title} has been deleted!"
      @item.destroy
    else
      flash[:notice] = "You are not authorized to do that!"
    end
    redirect_to admins_items_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]
  helper_method :user_reviewed?

  def index
    if !params.has_key?(:search)
      @items = Item.order(:title).page(params[:page])
    elsif params[:search] == ""
      flash[:error] = "Please enter a search term to search for products!"
      @items = Item.order(:title).page(params[:page])
    else
      @items = Item.search(params[:search]).order(:title).page(params[:page])
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new

    url = item_params[:item_url]

    if !validate_url(url)
      flash[:error] = "Please enter a valid Ikea product URL!"
      render :new and return
    end

    create_item(@item, url, item_params)

    if @item.save
      flash[:notice] = "Thanks for adding a new item to the site!"
      redirect_to @item
    elsif item_already_exists?
      original_item = Item.find_by(item_url: @item.item_url)
      flash[:notice] = "We've already got that one!  Here you go:"
      redirect_to original_item
    end
  end

  def show
    @item = Item.find(params[:id])
    @review = Review.new
    @reviews = @item.reviews.order(created_at: :desc).page(params[:page])
    @rating_options = Review::RATING_OPTIONS

    @headline = set_show_headline(@item, @reviews.count)
  end

  def item_params
    params.require(:item).permit(:item_url)
  end

  private

  def user_reviewed?
    @reviews = @item.reviews.order(created_at: :desc).page(params[:page])
    @users_who_reviewed = []

    @reviews.each do |review|
      @users_who_reviewed << review.user
    end

    @users_who_reviewed.include?(current_user)
  end

  def set_show_headline(item, review_count)
    headline = "Reviews"
    if review_count > 0
      headline += " - Average Review Score: #{item.calculate_average_review_score}"
    end
    headline
  end

  def create_item(item, url, item_params)
    item.item_url = item_params[:item_url]

    scraped_values = scrape_with_url(url)

    item.category = Category.find_or_create_by(name: scraped_values[:category])
    item.title = scraped_values[:title]
    item.subtitle = scraped_values[:subtitle]
    item.picture_url = scraped_values[:picture_url]
    item.price =  scraped_values[:price]
  end

  def validate_url(raw_url)
    ikea_regexp = /(^(http:\/\/)?www.ikea.com\/us\/en\/catalog\/products\/[A-z0-9]{3,10}\/$)/
    return false if raw_url.match(ikea_regexp).nil?
    url = URI(raw_url)
    res = Net::HTTP.get_response(url)
    return false if res.code != "200"
    true
  end

  def scrape_with_url(raw_url)
    url = URI(raw_url)
    raw_page = Net::HTTP.get(url)
    parsed_page = Nokogiri::HTML(raw_page)

    return_hash = {}

    return_hash[:title] = parsed_page.xpath('//div[@id="name"]').text.strip
    return_hash[:subtitle] = parsed_page.xpath('//div[@id="type"]').text.strip
    return_hash[:picture_url] = "http://www.ikea.com#{parsed_page.xpath('//img[@id="productImg"]//@src').text}"
    return_hash[:price] = parsed_page.xpath('//head//meta[@name="price"]//@content').text.delete("$").delete(",")
    return_hash[:category] = parsed_page.xpath('//head//meta[@name="IRWStats.categoryLocal"]//@content').text

    return_hash
  end

  def item_already_exists?
    @item.errors[:item_url][0] == "has already been taken"
  end

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "Please sign up to add a new item!"
      redirect_to new_user_registration_path
    end
  end
end

app/views/items/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Welcome to EyeKea!</title>
  </head>

  <body>
    <h1 class="text-center" id="greeting">Welcome to EyeKea!</h1>
    <h5 class="text-center" id="greeting">The premier review site for Ikea furniture</h5><br>
    <table class="hover">
      <thead>
        <tr>
          <th width="150">Ikea Item</th>
          <th width="200">Description</th>
        </tr>
      </thead>
      <tbody>
          <% @items.each do |item| %>
          <tr>
          <td><%= link_to item.title, item_path(item) %></td>
          <td><%= item.subtitle %></td>
        </tr>
          <% end %>
      </tbody>
    </table>
    <p>
      <%= paginate @items %>
    </p>
  </body>
</html>

app/views/items/new.html.erb
<br>
<h2 id="greeting">Please enter an Ikea URL</h2>

<%= form_for @item do |f|%>
  <%= f.label :item_url, "URL"%>
  <%= f.text_field :item_url %>

  <%= f.submit "Submit", class: "button" %>
<% end %>

app/views/items/show.html.erb
<h6 id="greeting">Category: <%= link_to @item.category.name, category_path(@item.category) %></h6>
<h1 id="greeting"><%= @item.title %></h1>
<h5 id="greeting"><%= @item.subtitle %></h5>
<h5 id="greeting"><%= @item.price %></h5>
<img id="item_picture" src="<%= @item.picture_url %>" alt="<%= @item.title %>" />

<div style="float:right">
<h4 id="greeting"><%= @headline %></h4>
<% if @reviews.empty? %>
  <p id="greeting">No reviews yet!</p>
<% else %>
  <ul id="review_list">
    <% @reviews.each_with_index do |review, index| %>
      <li id="review-<%= index %>">
        Rating: <%= review.rating %>
        <% if review.user == current_user %>
        <div class = "divider" style="float: right; width: 50px">
          <%= button_to "Edit", edit_item_review_path(@item, review),
            class: "button", method: :get
          %>
        </div>
        <div class = "divider" style="float: right; width: 70px">
            <%= button_to "Delete", item_review_path(@item, review),
              method: :delete, class: "alert button"
            %>
        </div>
        <% end %>
        <ul>
          <li style="white-space:pre-wrap; width:60ex">Description: <%= review.description %></li>
          <li class="review-rating" id="review-rating-<%= review.id %>">Review rating: <%= review.net_rating %></li>
          <li>
            Vote on this review:
            <%= link_to image_tag("https://s3.amazonaws.com/ikea-reviews/uploads/votes/thumbs_up.png"),
              votes_upvote_path(review_id: review.id),
              class: "vote_change upvote-#{index}",
              ajax_path: ajax_upvote_path(review_id: review.id)
            %>
            <%= link_to image_tag("https://s3.amazonaws.com/ikea-reviews/uploads/votes/thumbs_down.png"),
              votes_downvote_path(review_id: review.id),
              class: "vote_change downvote-#{index}",
              ajax_path: ajax_downvote_path(review_id: review.id)
            %>
          </li>
        </ul>
      </li>
    <% end %>
  </ul>
<% end %>

<%= paginate @reviews %>

<% unless current_user.nil? || user_reviewed? %>
  <div style="float:left">
    <h4 id="greeting">We'd love your review of the <%= @item.title %>!</h4>

    <%= form_for [@item, @review] do |f| %>
      <%= f.label :rating, "Rating:" %>
      <%= f.select :rating, options_for_select(@rating_options) %>

      <%= f.label :description, "Your Review:" %>
      <%= f.text_area :description %>
      <%= f.submit "Submit", class: "button" %>
    <% end %>
  </div>
<% end %>