config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    :controllers => { registrations: "devise/custom/registrations" }
  root "items#index"
  get "/votes/upvote", to: 'votes#upvote'
  get "/votes/downvote", to: 'votes#downvote'
  get "/ajax/upvote", to: 'votes#ajax_upvote'
  get "/ajax/downvote", to: 'votes#ajax_downvote'

  resources :categories, only: [:show]
  resources :items, only: [:new, :create, :index, :show] do
    resources :reviews, only: [:create, :update, :edit, :destroy]
  end
  resources :admins, only: [:index]
  namespace :admins do
    resources :users, only: [:index, :destroy]
    resources :items, only: [:index, :destroy]
    resources :reviews, only: [:index, :destroy]
  end
end

app/views/layouts/_navbar.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>&#x1F436;	&#x1f441; &#128273; &#128576;</li>

      <li><a href="/">Home &#127969;</a></li>
      <li><a href="/items/new">Add an Item</a></li>
      <li>
        <a href="#">View by Category</a>
        <ul class="menu vertical">
          <% categories_list.each do |category| %>
          <li><%= link_to category.name, category_path(category.id) %></li>
          <% end %>
        </ul>
      </li>
      <li class="has-form">
        <div class="row collapse">
          <div class="large-8 small-9 columns">
            <%= form_tag(items_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search]%>
          </div>
          <div class="large-4 small-3 columns">
            <%= submit_tag "Search!", name: nil, id: "search-button"%>
          </div>
          <% end %>
        </div>
      </li>
    </ul>
  </div>

  <div class="top-bar-right clearfix">
    <% if user_signed_in? %>
      <%= link_to 'Edit Profile', edit_user_registration_path %>
      |
      <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
      |
      <% if current_user.admin? %>
        <%= link_to "Admin Section", admins_path %>
        |
      <% end %>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path %>
      |
      <%= link_to "Log in", new_user_session_path %>
      |
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome to Eyekea!</title>
    <link href='https://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar', locals: {categories: categories_list} %>
    <div class="container-fluid">
      <div class="flash_message">
        <% flash.each do |key, value| %>
        <%= value %>
        <% end %>
      </div>
    </div>
    <div class="column">
      <%= yield %>
    </div>
  </body>
</html>